#!/usr/bin/env bun
/**
 * Reads src/content/blog/posts/*.md and emits posts.generated.ts so the
 * client bundle has post data without filesystem access at runtime.
 */
import { writeFile } from "fs/promises"
import path from "path"

const POSTS_DIR = path.resolve("src/content/blog/posts")
const OUT = path.resolve("src/content/blog/posts.generated.ts")

const files = [...new Bun.Glob("*.md").scanSync(POSTS_DIR)].sort()

const entries = await Promise.all(
  files.map(async (name) => {
    const raw = await Bun.file(path.join(POSTS_DIR, name)).text()
    const slug = name.replace(/\.md$/, "")
    return { slug, raw }
  }),
)

const body = `// Auto-generated by scripts/generate-blog.ts — do not edit.
export const RAW_BLOG_POSTS: readonly { readonly slug: string; readonly raw: string }[] = ${JSON.stringify(entries, null, 2)} as const
`

await writeFile(OUT, body, "utf8")
console.log(`📝 Generated ${path.relative(process.cwd(), OUT)} (${entries.length} posts)`)
